### ISSUE TITLE
`write()` doesn't work

### ISSUE THREAD

**Issue by dfdx** [tanmaykm/Elly.jl#21] opened 2016-06-06 15:04 UTC
When I try to run (a little bit modified) example from a README:

```
dfs = HDFSClient("<our-nameserver>", 8020)
dfspath = HDFSFile(dfs, "/tmp/testdir/testfile")
f = open(dfspath, "w")
write(f, b"hello world")
```

I get the following error:

```
ERROR: MethodError: `_add_block` has no method matching _add_block(::Elly.HDFSClient, ::ASCIIString)
  in _add_block at /home/username/.julia/v0.4/Elly/src/api_hdfs_base.jl:397
  in _write at /home/username/.julia/v0.4/Elly/src/api_hdfs_io.jl:295
  in write at /home/username/.julia/v0.4/Elly/src/api_hdfs_io.jl:314
```

I suppose the code just hasn't been updated after some refactoring, but I don't have enough knowledge of codebase to fix it myself.

**Comment by tanmaykm** [comment] 2016-06-06 15:07
Could you try on master and also including the commits in #20 
That was the latest I had found working.
Yes, it still needs to be merged and tagged.

**Comment by dfdx** [comment] 2016-06-06 15:23
Thanks for a quick reply. Changes you described fixed previous error, but now I'm getting a new one: 

```
 ERROR: Elly.HadoopRpcException(1,"Error flushing pipeline")
  in flush_and_wait at /home/username/.julia/v0.4/Elly/src/rpc.jl:745
  in close at /home/username/.julia/v0.4/Elly/src/api_hdfs_io.jl:323
```

I tried all 3 - latest master, PR #20 and master with merged PR. 

Just in case, we are using CDH 5.5.1 (Hadoop 2.6.+).

**Comment by tanmaykm** [comment] 2016-06-06 15:59
Hmm... I will try and reproduce that.
Could you give some more details like, which Julia version are you on and a set of steps that will likely reproduce this?

Also, it will be great if you could check if there is anything in the dfs logs which may give some clue. Thanks.

**Comment by dfdx** [comment] 2016-06-06 20:39
I'm using Julia 0.4.3. I don't do anything new except for closing the file, i.e. my code looks like:

```
dfs = HDFSClient("<our-nameserver>", 8020)
dfspath = HDFSFile(dfs, "/tmp/testdir/testfile")
f = open(dfspath, "w")
write(f, b"hello world")
close(f)
```

I don't have access to that Hadoop cluster right now, so will check logs tomorrow. I'll also try to set up HDFS docker image to see whether the problem is with the library or the Hadoop installation.

**Comment by dfdx** [comment] 2016-06-07 09:43
Quick update: I've checked namanode logs, but can't see anything with `ERROR` or even `WARN` lines. Note that reading files and closing after that works fine, so I suppose the issue is in writer. I'll try to debug it, though it may take time.

**Comment by tanmaykm** [comment] 2016-06-07 10:25
Thanks for checking. I think I have traced the issue. It's due to the use of `Base.unsafe_write` in `rpc.jl` which is not available on Julia v0.4.

Will push a fix soon.

**Comment by dfdx** [comment] 2016-06-07 12:01
I think you also need `using Compat` at the beginning to make `unsafe_write` available in Julia 0.4. With these 2 changes (`using Compat` and `Base.unsafe_write` => `unsafe_write`) example above worked for me. 

Thanks and feel free to close this issue once the changes are merged.

**Comment by tanmaykm** [comment] 2016-06-07 12:04
`using Compat` is already done here: https://github.com/JuliaParallel/Elly.jl/blob/b2378701da6ccb7b8a688a1dec146e32ed22e782/src/Elly.jl#L3

Doesn't that work?

**Comment by dfdx** [comment] 2016-06-07 12:14
Hmm, I saw it breaking, but can't reproduce it, so it should have been saved REPL state or somthing. Now everything works fine without additional `using Compat`, sorry for confusion.

**Comment by tanmaykm** [comment] 2016-06-07 13:57
OK. Thanks!

**Closed as completed** 2016-06-07 13:57 UTC
